### ISSUE TITLE
loadedmetadata event not firing

### ISSUE THREAD

**Issue by regenrek** [robertjanes/video-resize#2]
Hi,

awesome work on this library, like it very much!

I have some problems on a live site with the "loadedmetadata" event.
The same site works great on my local vagrant environment but fails on the live site.

Strange error, couldn't resolve this it. My workaround was to remove 
the EventListener - this worked.

```
 //element.addEventListener( "loadedmetadata", function (e) {
      video.ratio = getVideoRatio(element);
      videoSize(element, container.clientWidth, container.clientHeight, video.ratio, fit);
      toggleOpacity(element);
//    });
```

Regards Kevin.

**Comment by robertjanes** [comment]
Hey Kevin,

Thanks for catching that. In my usage ```loadedmetadata``` was working every time, but I realise that if you ```video.init()``` after the ```loadedmetadata``` has occurred it will not work.

So I've implemented a check using ```.readyState``` which either listens for the load or immediately initialises if the video is loaded already.

Here are the changes:
```javascript
function setOnLoad(video, element, container, fit) {
  // If video metadata not loaded, listen for load.
  // Else, check if already loaded.
  if (element.readyState === 0) {
    element.addEventListener( "loadedmetadata", function (e) {
      videoLoaded(video, element, container, fit);
    });
  } else if (element.readyState >= 1) {
    videoLoaded(video, element, container, fit);
  }
}
```

Can confirm these changes work in Chrome 49.0.2623.112, Safari 9.0.1, Firefox 45.0.2 and Opera 	36.0.2130.65.

Hope that fixes everything.

Happy to see others getting some use out of this library! Let me know if there are any features you'd like implemented, as I created this in around a week for a job and it currently works for what I needed, so I didn't really have anything planned.

Cheers,

Rob
