### ISSUE TITLE
Disable on mobile & Poster Feature

### ISSUE THREAD

**Issue by regenrek** [robertjanes/video-resize#3]
Hi,

1)

as you ask for feature request. I'm thinking of disabling video playback
on mobile because of perfomance.
This would mean you only add the video Tag dynamically if you aren't on
mobile.

Thats my approach to this (in jQuery):

```
  $.fn.videoBackground = function(video, callback) {
    var that = this;

    //append a video tag to the target element
    that.append($('<video id="vide-showreel">')
        .attr({'autoplay': 'autoplay', 'muted': 'muted', 'loop': 'loop'}));

   $("#vide-showreel").append($("<source>").attr({"src": video, type: "video/mp4"}));


    callback();
  }

    var mobileTest = false;

    if (/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent)) {
      mobileTest = true;
    }

    if(!mobileTest) {
      $('.fullscreen-video').videoBackground("#vide-showreel", function() {
        video = new videoResize({element: '#vide-showreel', fit: 'cover'});
        video.init();
      });
    }
 
```

HTML:

<div class="fullscreen-video"></div>

You think thats a good approach to solve this kind of problems?

2) Fullscreen Video - Image Fallback - thats something I'm missing here.

Regards Kevin

**Comment by robertjanes** [comment]
Hey Kevin,

I've spent the last few days looking into what will make mobile loading more efficient. I've come up with a bit of an experimental approach, it'll all be documented in the v0.6.6 release which I'll post later.

Could you explain what you mean for 2) in a bit more detail?

Cheers,

Rob

**Comment by regenrek** [comment]
The second seems just to be a image until the video loads.

> The poster image will be replaced by the first frame of the video once it loads, so it makes sense to derive that image from the same first frame.

<video autoplay loop poster="poster.jpg" id="bgvid"></video>

**Comment by regenrek** [comment]
Here is my finished approach to disable on mobile. It isn't very modular, so no real options
can be passed. Not good for public use

HTML

```
    <div class="fullscreen-video">
         data-background="<?php echo get_template_directory_uri()."/bg_image.jpg" ?>"
         data-video-src="showreel.mp4">
    </div>
```

JS

```
  $.fn.videoBackground = function(video, callback) {
    var that = this;

    var videoID = "#"+video;

    //append a video tag to the target element
    that.append($('<video id="'+video+'">')
        .attr({'autoplay': 'autoplay', 'muted': 'muted', 'loop': 'loop'}));

   $(videoID).append($("<source>").attr({"src": that.data("videoSrc"), type: "video/mp4"}));

    callback();
  }

  var fscreenVid   = $('.fullscreen-video');
  
  if(mobileTest) {
    fscreenVid.fadeIn("fast").videoBackground("vide-showreel", function() {
      video = new videoResize({element: '#vide-showreel', fit: 'cover'});
      video.init();
    });
 } else {
      // mobile stuff
      fscreenVid.css({"background-image" : 'url('+fscreenVid.data("background")+')'});
    }
```

**Comment by robertjanes** [comment]
I've just updated it to v0.6.6 which will do all this automatically. So what you can do is leave the ```<source``` tags out of the ```<video>``` and add them as a ```sources``` argument, like this:

```javascript
video = new videoResize({element: '#vide-showreel', sources: 'video.mp4'});
```

And then your ```<video>``` tag would be like this:

```html
<video id="vide-showreel" poster="video.jpg" autoplay loop></video>
```

Then using the ```mobileBreak``` option specify the screen width at which you want to transfer to the mobile layout.

```javascript
video = new videoResize({element: '#vide-showreel', sources: 'video.mp4', mobileBreak: 480});
```

Hope that works, let me know.

R
